import slugify from 'slugify';
import template from './werkl-blog-detail.html.twig';
import BLOG from '../../constant/open-blogware.constant';

const { Context, ExtensionAPI } = Shopware;
const { Criteria } = Shopware.Data;
const { debounce } = Shopware.Utils;
const { cloneDeep } = Shopware.Utils.object;
const { ShopwareError } = Shopware.Classes;
const debounceTimeout = 300;

export default {
    template,

    data() {
        return {
            blogId: null,
            blog: null,
            originalSlug: null,
            isLoading: false,
            localeLanguage: null,
            showSectionModal: false,
            sectionDontRemind: false,
            slugManuallyEdited: false,
            autoGeneratedSlug: null,
            isAutoGenerating: false,
        };
    },

    computed: {
        identifier() {
            return this.placeholder(this.blog, 'title');
        },

        blogRepository() {
            return this.repositoryFactory.create('werkl_blog_entry');
        },

        mediaRepository() {
            return this.repositoryFactory.create('media');
        },

        localeRepository() {
            return this.repositoryFactory.create('locale');
        },

        loadBlogCriteria() {
            const criteria = new Criteria(1, 1);
            const sortCriteria = Criteria.sort('position', 'ASC', true);

            criteria
                .addAssociation('blogCategories')
                .addAssociation('tags')

                .getAssociation('cmsPage')
                .getAssociation('sections')
                .addSorting(sortCriteria)
                .addAssociation('backgroundMedia')

                .getAssociation('blocks')
                .addSorting(sortCriteria)
                .addAssociation('backgroundMedia')
                .addAssociation('slots');

            return criteria;
        },

        backPath() {
            if (this.$route.query.ids && this.$route.query.ids.length > 0) {
                return {
                    name: 'blog.module.index',
                    query: {
                        ids: this.$route.query.ids,
                        limit: this.$route.query.limit,
                        page: this.$route.query.page,
                    },
                };
            }
            return { name: 'blog.module.index' };
        },

        isCreateMode() {
            return this.$route.name === 'blog.module.create';
        },

        salesChannelRepository() {
            return this.repositoryFactory.create('sales_channel');
        },
    },

    watch: {
        'blog.title': function (blogTitle) {
            this.onBlogTitleChanged(blogTitle);
        },
        'blog.slug': function (newSlug) {
            // Only mark as manually edited if we're not currently auto-generating
            // For new blogs (autoGeneratedSlug is null), any slug value means manual edit
            // For existing blogs or after first auto-generation, check if different from auto-generated
            if (!this.isAutoGenerating) {
                if (this.autoGeneratedSlug === null || this.autoGeneratedSlug === undefined) {
                    // New blog: if user types a slug before auto-generation, mark as manual
                    if (newSlug) {
                        this.slugManuallyEdited = true;
                    }
                } else if (newSlug !== this.autoGeneratedSlug) {
                    // Existing blog or after auto-generation: check if different
                    this.slugManuallyEdited = true;
                }
            }
        },
    },

    methods: {
        createdComponent() {
            this.publishExtensionData();
            Shopware.Store.get('adminMenu').collapseSidebar();

            const isSystemDefaultLanguage = Shopware.Store.get('context').isSystemDefaultLanguage;
            this.cmsPageState.setIsSystemDefaultLanguage(isSystemDefaultLanguage);

            this.resetCmsPageState();

            if (this.$route.params.id) {
                this.isLoading = true;
                this.blogId = this.$route.params.id;

                Shopware.Store.get('shopwareApps').selectedIds = [this.pageId];

                const criteria = new Criteria(1, 25);
                criteria.addFilter(
                    Criteria.equals('typeId', Shopware.Defaults.storefrontSalesChannelTypeId),
                );

                this.salesChannelRepository.search(criteria).then((response) => {
                    this.salesChannels = response;

                    if (this.salesChannels.length > 0) {
                        this.currentSalesChannelKey = this.salesChannels[0].id;
                        this.loadBlog(this.blogId);
                    }
                });
            }
            this.setPageContext();
        },

        publishExtensionData() {
            ExtensionAPI.publishData({
                id: 'werkl-blog-detail__page',
                path: 'page',
                scope: this,
            });

            ExtensionAPI.publishData({
                id: 'werkl-blog-detail__blog',
                path: 'blog',
                scope: this,
            });
        },

        /**
         * Debounced wrapper for the savePage function
         */
        debouncedPageSave: debounce(function debouncedOnSave() {
            this.onSave();
        }, debounceTimeout),

        loadBlog(blogId) {
            this.isLoading = true;

            return this.blogRepository.get(blogId, Context.api, this.loadBlogCriteria).then((entity) => {
                this.blog = entity;
                this.originalSlug = entity.slug;
                // For existing blogs, mark slug as manually edited to prevent auto-updates
                // This ensures URL stability for published content
                this.slugManuallyEdited = true;
                // Initialize auto-generated slug with the current slug
                this.autoGeneratedSlug = entity.slug;

                if (this.blog.translated.mediaId) {
                    this.mediaRepository.get(this.blog.translated.mediaId).then((media) => {
                        this.blog.media = media;
                    });
                }

                if (entity.cmsPageId) {
                    this.page = entity.cmsPage;
                    this.pageId = entity.cmsPageId;
                    this.cmsPageState.setCurrentPageType(this.page.type);
                    delete this.blog.cmsPage;
                    return this.loadCMSDataResolver();
                } else {
                    this.isLoading = false;
                    this.createPage(entity.title);
                    this.blog.cmsPageId = this.page.id;
                    this.blogId = entity.id;
                    return this.loadCMSDataResolver();
                }
            }).catch((exception) => {
                this.isLoading = false;
                this.createNotificationError({
                    title: exception.message,
                    message: exception.response,
                });
            });
        },

        onPageSave(debounced = false) {
            this.onPageUpdate();

            if (debounced) {
                this.debouncedPageSave();
                return;
            }

            this.onSaveBlog();
        },

        addAdditionalSection(type, index) {
            this.onAddSection(type, index);
        },

        async onChangeLanguage() {
            this.isLoading = true;

            return this.salesChannelRepository.search(new Criteria()).then((response) => {
                this.salesChannels = response;
                const isSystemDefaultLanguage = Shopware.Store.get('context').isSystemDefaultLanguage;
                this.cmsPageState.setIsSystemDefaultLanguage(isSystemDefaultLanguage);
                return this.loadBlog(this.blogId);
            });
        },

        saveOnLanguageChange() {
            return this.onSaveBlog();
        },

        loadCMSDataResolver() {
            this.isLoading = true;

            return this.cmsDataResolverService.resolve(this.page).then(() => {
                this.updateSectionAndBlockPositions();
                this.cmsPageState.setCurrentPage(this.page);

                this.updateDataMapping();
                this.pageOrigin = cloneDeep(this.page);

                if (this.selectedBlock) {
                    const blockId = this.selectedBlock.id;
                    const blockSectionId = this.selectedBlock.sectionId;
                    this.page.sections.forEach((section) => {
                        if (section.id === blockSectionId) {
                            section.blocks.forEach((block) => {
                                if (block.id === blockId) {
                                    this.setSelectedBlock(blockSectionId, block);
                                }
                            });
                        }
                    });
                }

                this.isLoading = false;
            }).catch((exception) => {
                this.isLoading = false;

                this.createNotificationError({
                    title: exception.message,
                    message: exception.response,
                });

                warn(this._name, exception.message, exception.response);
            });
        },

        onSaveBlog() {
            if (!this.blogIsValid()) {
                this.createNotificationError({
                    message: this.$tc('werkl-blog.detail.notification.error.blogInvalid'),
                });

                this.$refs.cmsSidebar.$refs.blogConfigSidebar.openContent();

                return Promise.reject();
            }

            if (!this.pageIsValid()) {
                this.createNotificationError({
                    message: this.$tc('sw-cms.detail.notification.pageInvalid'),
                });

                return Promise.reject();
            }

            return this.onSavePageEntity()
                .then(() => this.onSaveBlogEntity())
                .then(() => this.loadBlog(this.blogId))
                .catch(exception => {
                    this.isLoading = false;

                    this.createNotificationError({
                        message: this.$tc('global.notification.unspecifiedSaveErrorMessage'),
                    });

                    return Promise.reject(exception);
                });
        },

        onSaveBlogEntity() {
            this.isLoading = true;

            return this.blogRepository.save(this.blog)
                .catch(exception => {
                    return Promise.reject(exception);
                }).finally(() => {
                    this.isLoading = false;
                });
        },

        onSavePageEntity() {
            this.isLoading = true;
            this.deleteEntityAndRequiredConfigKey(this.page.sections);

            return this.pageRepository.save(this.page).then(() => {
                this.isLoading = false;
                this.isSaveSuccessful = true;

                return Promise.resolve();
            }).catch((exception) => {
                return Promise.reject(exception);
            }).finally(() => {
                this.isLoading = false;
            });
        },

        blogIsValid() {
            Shopware.Store.get('error').resetApiErrors();

            return [
                this.missingTitleValidation(),
                this.missingPublishedAtValidation(),
                this.missingAuthorIdValidation(),
                this.missingCategoriesValidation(),
            ].every(validation => validation);
        },

        missingTitleValidation() {
            if (!this.isSystemDefaultLanguage || this.blog.title) {
                return true;
            }

            this.addBlogError({
                property: 'title',
                message: this.$tc('sw-cms.detail.notification.messageMissingFields'),
            });

            return false;
        },

        missingPublishedAtValidation() {
            if (this.blog.publishedAt) {
                return true;
            }

            this.addBlogError({
                property: 'publishedAt',
                message: this.$tc('sw-cms.detail.notification.messageMissingFields'),
            });

            return false;
        },

        missingAuthorIdValidation() {
            if (this.blog.authorId) {
                return true;
            }

            this.addBlogError({
                property: 'authorId',
                message: this.$tc('sw-cms.detail.notification.messageMissingFields'),
            });

            return false;
        },

        missingCategoriesValidation() {
            if (this.blog.blogCategories && this.blog.blogCategories.length) {
                return true;
            }

            this.addBlogError({
                property: 'blogCategories',
                message: this.$tc('sw-cms.detail.notification.messageMissingFields'),
            });

            return false;
        },

        pageSectionCountValidation() {
            return true;
        },

        onBlogTitleChanged: debounce(function (blogTitle) {
            if (!blogTitle) {
                return;
            }

            this.page.name = blogTitle;
            this.getLocaleLanguage();

            // Only auto-generate slug if:
            // 1. The slug is empty (new blog entry)
            // 2. OR the slug hasn't been manually edited (still matches auto-generated format)
            if (!this.blog.slug || !this.slugManuallyEdited) {
                this.generateSlug(blogTitle);
            }
        }, debounceTimeout),

        addBlogError({
            property = null,
            payload = {},
            code = BLOG.REQUIRED_FIELD_ERROR_CODE,
            message = '',
        } = {}) {
            const expression = `werkl_blog_entry.${this.blog.id}.${property}`;
            const error = new ShopwareError({
                code,
                detail: message,
                meta: { parameters: payload },
            });

            Shopware.Store.get('error').addApiError({
                expression,
                error,
            });
        },

        getLocaleLanguage() {
            return this.localeRepository.get(Context.api.language.localeId).then((result) => {
                this.localeLanguage = result.code.substr(0, result.code.length - 3).toLowerCase();
                return Promise.resolve(this.localeLanguage);
            });
        },

        generateSlug(value) {
            if (!value) {
                return;
            }

            const slug = slugify(value, {
                locale: this.localeLanguage,
                lower: true,
            });

            // Mark that we're auto-generating to avoid triggering manual edit detection
            this.isAutoGenerating = true;

            if (!this.localeLanguage) {
                this.blog.slug = slug;
                this.autoGeneratedSlug = slug;
                this.isAutoGenerating = false;
                return;
            }

            const criteria = new Criteria();
            criteria.addFilter(Criteria.equals('slug', slug));

            this.blogRepository.search(criteria).then((blogs) => {
                const articlesWithSameSlugCount = blogs.length;
                const isSlugUpdated = this.originalSlug !== slug;

                if (articlesWithSameSlugCount && isSlugUpdated) {
                    this.blog.slug = slug + '-' + '1';
                } else {
                    this.blog.slug = slug;
                }

                // After auto-generating, store this as the expected auto-generated slug
                this.autoGeneratedSlug = this.blog.slug;
                this.isAutoGenerating = false;
            }).catch(() => {
                this.blog.slug = slug;
                this.autoGeneratedSlug = this.blog.slug;
                this.isAutoGenerating = false;
            });
        },

        createPage(name) {
            this.page = this.pageRepository.create();
            this.page.name = name;
            this.page.type = BLOG.PAGE_TYPES.BLOG_DETAIL;
            this.page.sections = [];
            this.pageId = this.page.id;
        },
    },
};
