name: Build Plugin

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    if: github.event_name != 'push' || github.ref != 'refs/heads/main'
    uses: FriendsOfShopware/actions/.github/workflows/github.yml@main
    with:
      extensionName: WerklOpenBlogware
      shopwareVersion: 6.7.0
      cliVersion: latest
    secrets:
      ghToken: ${{ secrets.GITHUB_TOKEN }}

  build-main:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    uses: FriendsOfShopware/actions/.github/workflows/github.yml@main
    with:
      extensionName: WerklOpenBlogware
      shopwareVersion: 6.7.0
      cliVersion: latest
    secrets:
      ghToken: ${{ secrets.GITHUB_TOKEN }}
