name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  phpecs:
    name: Easy code standard
    runs-on: ubuntu-latest

    steps:
      - name: Clone Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Dependencies
        run: make dev -B

      - name: Run ecs
        run: make ecs -B

  phpcsfixer:
    name: PHP CS Fixer
    needs: phpecs
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Dependencies
        run: make dev -B

      - name: Run PHP CS Fixer
        run: make csfix -B

  phpstan:
    name: Static Analyzers
    needs: phpcsfixer
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Dependencies
        run: make dev -B

      - name: Run PHPStan
        run: make stan -B

  integration:
    name: Integration Tests | Shopware ${{ matrix.shopware }}
    needs: phpstan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shopware: [ '6.6.0.0',]
    steps:
      - name: Clone Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install PROD Dependencies
        run: make dev -B

      - name: Start Docker
        run: |
          docker run --rm --name shop --env PHP_VERSION=8.2 -d dockware/dev:${{ matrix.shopware }}
          sleep 30
          docker logs shop
      - name: Upload into Docker
        run: |
          docker cp $(pwd)/. shop:/var/www/html/custom/plugins/WerklOpenBlogware
          docker exec shop bash -c 'sudo chown www-data:www-data /var/www/html/custom/plugins -R'
      - name: Install and Build Plugin
        run: |
          docker exec shop bash -c 'cd /var/www/html/custom/plugins/WerklOpenBlogware && make clean'
          docker exec shop bash -c 'cd /var/www/html/custom/plugins/WerklOpenBlogware && make install'
          docker exec shop bash -c 'cd /var/www/html/custom/plugins/WerklOpenBlogware && make build'
