name: Snippets

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'src/**/snippet/*.json'
      - 'src/Resources/snippet/*/*.json'
  workflow_dispatch:

jobs:
  check:
    name: Snippets
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install compare-json
        run: npm install -g compare-json

      - name: Compare Administration JSON files
        run: comparejson -e -s="/" ./src/**/snippet/*.json

      - name: Compare Storefront JSON files
        run: comparejson -e -g="(\w+)\.[a-z]{2}\-[A-Z]{2}\.json$" ./src/Resources/snippet/*/*.json
