name: Tests
on:
  pull_request:
    paths:
      - '**/*.php'
  push:
    branches:
      - main
    paths:
      - '**/*.php'
  workflow_dispatch:

jobs:
  phpunit:
    uses: lacknere/shopware-github-actions/.github/workflows/phpunit.yml@allow-insecure-versions
    with:
      extensionName: WerklOpenBlogware
      shopwareVersion: 6.7.0.0
